name: feature_architecture_template
description: A new Flutter project.

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.18.2 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  hooks_riverpod: ^2.2.0
  go_router: ^5.0.5
  json_annotation: ^4.7.0
  freezed_annotation: ^2.1.0
  freezed: ^2.1.1
  build_runner: ^2.2.1
  mockito: ^5.3.2
  shared_preferences: ^2.0.15
  intl: ^0.17.0
  logger: ^1.1.0
  flutter_native_splash: ^2.2.10+1
  url_launcher: ^6.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.10.0
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family: RocknRoll_One
      fonts:
        - asset: assets/fonts/RocknRoll_One/RocknRollOne-Regular.ttf
    - family: Yusei_Magic
      fonts:
        - asset: assets/fonts/Yusei_Magic/YuseiMagic-Regular.ttf
    - family: Noto_Sans_JP
      fonts:
        - asset: assets/fonts/Noto_Sans_JP/NotoSansJP-Regular.otf
    - family: Zen_Maru_Gothic
      fonts:
        - asset: assets/fonts/Zen_Maru_Gothic/ZenMaruGothic-Regular.ttf
    - family: LINE_Seed_JP
      fonts:
        - asset: assets/fonts/LINE_Seed_JP/App/OTF/LINESeedJP_A_OTF_Rg.otf

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/icon.png"
