name: feature_architecture_template
description: A new Flutter project.

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.18.2 <3.0.0"
dependencies:
  build_runner: ^2.2.1
  cached_network_image: ^3.2.3
  collection: ^1.17.0
  dio: ^5.1.1
  encrypt: ^5.0.1
  flutter:
    sdk: flutter
  flutter_hooks: ^0.18.6
  flutter_native_splash: ^2.2.16
  freezed: ^2.1.1
  freezed_annotation: ^2.1.0
  go_router: ^5.0.5
  hashids2: ^2.0.0
  hooks_riverpod: ^2.2.0
  intl: ^0.17.0
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  json_annotation: ^4.7.0
  logger: ^1.1.0
  mockito: ^5.4.0
  path_provider: ^2.0.15
  retrofit: ^4.0.1
  riverpod_annotation: ^2.1.0
  riverpod_generator: ^2.1.5
  riverpod_lint: ^1.0.1
  shared_preferences: ^2.0.15
  url_launcher: ^6.1.6
  uuid: ^3.0.7

dev_dependencies:
  flutter_launcher_icons: ^0.10.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  isar_generator: ^3.1.0+1

flutter:
  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family: RocknRoll_One
      fonts:
        - asset: assets/fonts/RocknRoll_One/RocknRollOne-Regular.ttf
    - family: Yusei_Magic
      fonts:
        - asset: assets/fonts/Yusei_Magic/YuseiMagic-Regular.ttf
    - family: Noto_Sans_JP
      fonts:
        - asset: assets/fonts/Noto_Sans_JP/NotoSansJP-Regular.otf
    - family: Zen_Maru_Gothic
      fonts:
        - asset: assets/fonts/Zen_Maru_Gothic/ZenMaruGothic-Regular.ttf
    - family: LINE_Seed_JP
      fonts:
        - asset: assets/fonts/LINE_Seed_JP/App/OTF/LINESeedJP_A_OTF_Rg.otf

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/icon.png"

flutter_native_splash:
  image: "assets/images/kurogoma-splash.png"
  color: "D8D8D8"